version: '3.8'

services:
  whisper-bot:
    build: .
    container_name: telegram-whisper-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - whisper-tmp:/app/tmp
      - whisper-cache:/home/botuser/.cache/huggingface # 💾 ¡Guarda el modelo aquí!