#!/bin/bash
#USE THIS ONLY IF YOU RUN A STANDALONE INSTALLATION (DONT RUN FROM DOCKER)
export TELEGRAM_BOT_TOKEN=
export ALLOWED_CHAT_IDS=
export WHISPER_MODEL=tiny
export AUDIO_LANGUAGE=auto
python3 main.py
